### ISSUE TITLE
подключить звуки

### ISSUE THREAD

**Issue by davojta** [mathworld-games/math-game-web#14]
надо играть звук клавиш
И может на когда правильно какой приятный звук
+ фоновый звук какой пожеланию
+ нарисовать иконку чтобы выключить звук

можно попробывать миди какое 

потом с дизайнеркой подберем финальные звуки

**Comment by AlesiaGit** [comment]
fixed in https://github.com/mathworld-games/math-game-web/pull/18

**Comment by davojta** [comment]
Сделано!
