### ISSUE TITLE
Экран регистрации пользователя

### ISSUE THREAD

**Issue by davojta** [mathworld-games/math-game-web#15]
При старте игры должен запускаться экран регистрации пользователя

![image](https://user-images.githubusercontent.com/893650/32872957-8e080674-ca9a-11e7-8705-0e7ce82e9fe8.png)

1) меню новый пользователь создает нового пользователя
* при выборе открывается экран ввода слова
* просле ввода слова открывается экран подбора сложности
![image](https://user-images.githubusercontent.com/893650/32873274-2b998a60-ca9c-11e7-8781-85b1044a6b9d.png)
* потом открывается экран с 3 примерами, которые указаны в конфиге
![image](https://user-images.githubusercontent.com/893650/32873289-4896a60c-ca9c-11e7-8241-6102575d5c9d.png)
По результатам которого определяется сложность игры

2) после новый пользователь - список людей, которые уже играли на этом устройстве
при клики открывается их сохраннёная сессия, доступны достижения

**Comment by AlesiaGit** [comment]
fixed in https://github.com/mathworld-games/math-game-web/pull/18

**Comment by davojta** [comment]
Сделано!
