### ISSUE TITLE
Новая подигра - задача

### ISSUE THREAD

**Issue by davojta** [mathworld-games/math-game-web#16]
Нужно реализовать новую подигру - ответ на задачу
![image](https://user-images.githubusercontent.com/893650/32873073-1eb73e92-ca9b-11e7-988b-53fe341c6172.png)

Задача состоит из 
*  текста 
* картинки
* ответа

1) текст задачи должен быть указан в файле
на первой стадии ответ хардкодится и указывается рядом с текстом задачи

2) задача должна показываться после 2 примеров 
впоследствии порядок появления задач и примеров будет задаваться в конфиге уровней

3) ответ на задачу защитывается как ответ на пример

4) время на задачу - 5 мин

**Comment by davojta** [comment]
Пример задач:

Бабушка Зина собрала в лесу 5 килограммов грибов. Бабушка Люда 10 килограммов. Проверка показала, что все грибы радиоактивны.  Сколько килограммов белых грибов выкинули обе бабушки с громким вздохом?

Костя собрал 12 килограммов грибов. Когда бабушка выкинула из его корзинки все ядовитые грибы, у Кости осталось только 3 килограмма грибов. Сколько килограммов несъедобных гибов собрал Костя.

Катя тайком съела 3 розочки на праздничном торте. Лёша съел 5 розочек. Сколько было розочек на торте, если вечером папа долго удивлялся, почему современные торты совсем ничем не украшают.

**Comment by AlesiaGit** [comment]
fixed in https://github.com/mathworld-games/math-game-web/pull/18

**Comment by davojta** [comment]
Сделано! Закрываю!
