### ISSUE TITLE
Новая подигра - примеры с вариантами ответа

### ISSUE THREAD

**Issue by davojta** [mathworld-games/math-game-web#17]
Необходимо реализовать подигру с вариантами ответов

То есть это обычный пример у которого есть 4 варианта (вместо клавиатуры область экрана делится на 4 части - рандомно распределяются правильный \ неправильные ответы )

**Comment by AlesiaGit** [comment]
fixed in https://github.com/mathworld-games/math-game-web/pull/18

**Comment by AlesiaGit** [comment]
fixed in https://github.com/mathworld-games/math-game-web/pull/18

**Comment by vvscode** [comment]
@davojta  можно закрывать?

**Comment by davojta** [comment]
@vvscode  ДА! Позакрываю таски!
